# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14995493b9dc31ce7e53f033d35cc440cae7d9bf8a264d6d637fce2c1283d48d20d95ac8d2bab1934a5cffc542331cca8137b1dae867ab4d9c467de4475d4d34

test:
  secret_key_base: 54a8aa67a56a265bf827f09829492b3bf6d56e8c2aff032b3b918c789729a7149feefb11b08f8fc91ed4a1d37a008106033c394b02e908e307c86d390de96801

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
